### ISSUE TITLE
Information on vegetation type

### ISSUE THREAD

**Issue by Alectoria** [gustavobio/flora#3]
Hi Gustavo,

I've noticed on the Flora do Brazil 2020 homepage, that vegetation is displayed for every species ('Tipo de Vegetação'). For example, for 'Miconia albicans', you would get "Área Antrópica, Campinarana, Campo Rupestre, Carrasco, Cerrado (lato sensu), Floresta Estacional Semidecidual, Restinga, Savana Amazônica"

Is it possible to access this information from your package? 

Thanks for all the effort with this nice package!

**Comment by gustavobio** [comment]
Hi Viktoria, thanks for bringing this up. If I recall correctly, there is a function I introduced in one of the latest commits that might do this: `get_domains`. I can't be sure now because flora do brasil is down for me and they don't distribute this info in the provided DWC files. You have to scrape the page for it. I'll take a look into it as soon as it's back up. Cheers!

**Comment by gustavobio** [comment]
Okay so now you can grab the info you want with `get_vegtype()`. You have to install the package from github to see the new function. Thanks again.

**Comment by Alectoria** [comment]
Thanks a lot Gustavo! Very exciting! - Server seems to be down right now. Will try it out once it is up, again.
